SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA learn_language;


SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE learn_language.cards (
    difficulty real,
    stability real,
    state integer NOT NULL,
    step integer,
    due timestamp(6) without time zone NOT NULL,
    last_review timestamp(6) without time zone,
    data jsonb NOT NULL,
    id character varying(255) NOT NULL,
    source_id character varying(255) NOT NULL,
    source_page_number integer NOT NULL
);


CREATE TABLE learn_language.review_logs (
    id integer NOT NULL,
    rating integer NOT NULL,
    review_duration integer,
    review_datetime timestamp(6) without time zone NOT NULL,
    card_id character varying(255) NOT NULL
);


ALTER TABLE learn_language.review_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME learn_language.review_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE learn_language.sources (
    bookmarked_page integer,
    start_page integer,
    file_name character varying(255),
    id character varying(255) NOT NULL,
    name character varying(255)
);


INSERT INTO learn_language.sources (bookmarked_page, start_page, file_name, id, name) VALUES (NULL, 16, 'Goethe-Zertifikat_B1_Wortliste.pdf', 'goethe-b1', 'Goethe B1');
INSERT INTO learn_language.sources (bookmarked_page, start_page, file_name, id, name) VALUES (9, 9, 'A1_SD1_Wortliste_02.pdf', 'goethe-a1', 'Goethe A1');
INSERT INTO learn_language.sources (bookmarked_page, start_page, file_name, id, name) VALUES (8, 8, 'Goethe-Zertifikat_A2_Wortliste.pdf', 'goethe-a2', 'Goethe A2');


SELECT pg_catalog.setval('learn_language.review_logs_id_seq', 1, false);


ALTER TABLE ONLY learn_language.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);


ALTER TABLE ONLY learn_language.review_logs
    ADD CONSTRAINT review_logs_pkey PRIMARY KEY (id);


ALTER TABLE ONLY learn_language.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);


ALTER TABLE ONLY learn_language.review_logs
    ADD CONSTRAINT fk6qudadb9cdv57kh9g3khyench FOREIGN KEY (card_id) REFERENCES learn_language.cards(id);


ALTER TABLE ONLY learn_language.cards
    ADD CONSTRAINT fkjei36iycub8pvhosmh0nuqskm FOREIGN KEY (source_id) REFERENCES learn_language.sources(id);
