CREATE SCHEMA IF NOT EXISTS learn_language;

CREATE TABLE IF NOT EXISTS learn_language.sources (
    id character varying(255) NOT NULL,
    bookmarked_page integer,
    start_page integer,
    name character varying(255),
    language_level character varying(255),
    card_type character varying(255),
    format_type character varying(255),
    source_type character varying(255),
    CONSTRAINT sources_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS learn_language.documents (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_id character varying(255) NOT NULL,
    file_name character varying(255) NOT NULL,
    page_number integer,
    CONSTRAINT documents_pkey PRIMARY KEY (id),
    CONSTRAINT document_source_id_fkey FOREIGN KEY (source_id) REFERENCES learn_language.sources(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS learn_language.cards (
    id character varying(255) NOT NULL,
    source_id character varying(255) NOT NULL,
    source_page_number integer NOT NULL,
    data jsonb NOT NULL,
    readiness character varying(255) NOT NULL,
    due timestamp(6) NOT NULL,
    stability real NOT NULL,
    difficulty real NOT NULL,
    elapsed_days real NOT NULL,
    scheduled_days real NOT NULL,
    learning_steps integer NOT NULL,
    reps integer NOT NULL,
    lapses integer NOT NULL,
    state character varying(255) NOT NULL,
    last_review timestamp(6),
    CONSTRAINT cards_pkey PRIMARY KEY (id),
    CONSTRAINT card_source_id_fkey FOREIGN KEY (source_id) REFERENCES learn_language.sources(id)
);

CREATE TABLE IF NOT EXISTS learn_language.learning_partners (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    CONSTRAINT learning_partners_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS learn_language.review_logs (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    rating integer NOT NULL,
    review_duration integer,
    review timestamp(6) NOT NULL,
    card_id character varying(255) NOT NULL,
    state character varying(255) NOT NULL,
    due timestamp(6) NOT NULL,
    stability float8 NOT NULL,
    difficulty float8 NOT NULL,
    elapsed_days float8 NOT NULL,
    last_elapsed_days float8,
    scheduled_days float8 NOT NULL,
    learning_steps integer,
    learning_partner_id integer,
    CONSTRAINT review_logs_pkey PRIMARY KEY (id),
    CONSTRAINT review_log_card_id_fkey FOREIGN KEY (card_id) REFERENCES learn_language.cards(id),
    CONSTRAINT review_log_learning_partner_fkey FOREIGN KEY (learning_partner_id) REFERENCES learn_language.learning_partners(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS learn_language.model_usage_logs (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_name character varying(255) NOT NULL,
    model_type character varying(50) NOT NULL,
    operation_type character varying(255) NOT NULL,
    operation_id character varying(255),
    input_tokens bigint,
    output_tokens bigint,
    input_characters bigint,
    image_count integer,
    cost_usd numeric(10, 6),
    processing_time_ms bigint,
    response_content text,
    rating integer,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT model_usage_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS learn_language.voice_configurations (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    voice_id character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    language character varying(10) NOT NULL,
    display_name character varying(255),
    is_enabled boolean NOT NULL DEFAULT true,
    CONSTRAINT voice_configurations_pkey PRIMARY KEY (id),
    CONSTRAINT voice_configurations_unique UNIQUE (voice_id, language, model)
);

CREATE TABLE IF NOT EXISTS learn_language.chat_model_settings (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_name character varying(255) NOT NULL,
    operation_type character varying(255) NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    is_primary boolean NOT NULL DEFAULT false,
    CONSTRAINT chat_model_settings_pkey PRIMARY KEY (id),
    CONSTRAINT chat_model_settings_unique UNIQUE (model_name, operation_type)
);

CREATE TABLE IF NOT EXISTS learn_language.known_words (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    word character varying(255) NOT NULL,
    hungarian_translation character varying(255),
    CONSTRAINT known_words_pkey PRIMARY KEY (id),
    CONSTRAINT known_words_unique UNIQUE (word)
);

CREATE TABLE IF NOT EXISTS learn_language.study_sessions (
    id character varying(255) NOT NULL,
    source_id character varying(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    study_mode character varying(50) NOT NULL DEFAULT 'SOLO',
    CONSTRAINT study_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT study_session_source_fkey FOREIGN KEY (source_id) REFERENCES learn_language.sources(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS study_sessions_source_date_idx
    ON learn_language.study_sessions (source_id, ((created_at::date)));

CREATE TABLE IF NOT EXISTS learn_language.study_session_cards (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    session_id character varying(255) NOT NULL,
    card_id character varying(255) NOT NULL,
    position integer NOT NULL,
    learning_partner_id integer,
    version integer DEFAULT 0,
    CONSTRAINT study_session_cards_pkey PRIMARY KEY (id),
    CONSTRAINT study_session_cards_session_fkey FOREIGN KEY (session_id) REFERENCES learn_language.study_sessions(id) ON DELETE CASCADE,
    CONSTRAINT study_session_cards_card_fkey FOREIGN KEY (card_id) REFERENCES learn_language.cards(id) ON DELETE CASCADE,
    CONSTRAINT study_session_cards_partner_fkey FOREIGN KEY (learning_partner_id) REFERENCES learn_language.learning_partners(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS cards_last_review_idx ON learn_language.cards (last_review);
CREATE INDEX IF NOT EXISTS review_logs_card_review_idx ON learn_language.review_logs (card_id, review DESC);

CREATE INDEX IF NOT EXISTS idx_cards_readiness_due ON learn_language.cards (readiness, due)
    WHERE readiness = 'READY';
CREATE INDEX IF NOT EXISTS idx_cards_source_readiness ON learn_language.cards (source_id, readiness);

CREATE MATERIALIZED VIEW IF NOT EXISTS learn_language.card_view AS
SELECT
    c.id,
    c.source_id,
    c.source_page_number,
    c.data,
    c.readiness,
    c.due,
    c.stability,
    c.difficulty,
    c.elapsed_days,
    c.scheduled_days,
    c.learning_steps,
    c.reps,
    c.lapses,
    c.state,
    c.last_review,
    s.name AS source_name,
    s.source_type,
    s.language_level,
    s.card_type,
    s.format_type,
    s.start_page AS source_start_page,
    s.bookmarked_page AS source_bookmarked_page,
    lr.rating AS last_review_rating,
    lp.name AS last_review_learning_partner_name
FROM learn_language.cards c
JOIN learn_language.sources s ON c.source_id = s.id
LEFT JOIN LATERAL (
    SELECT rating, learning_partner_id
    FROM learn_language.review_logs
    WHERE card_id = c.id
    ORDER BY review DESC
    LIMIT 1
) lr ON true
LEFT JOIN learn_language.learning_partners lp ON lr.learning_partner_id = lp.id;

CREATE UNIQUE INDEX IF NOT EXISTS card_view_id_idx ON learn_language.card_view (id);
