CREATE SCHEMA IF NOT EXISTS learn_language;

CREATE TABLE IF NOT EXISTS learn_language.sources (
    id character varying(255) NOT NULL,
    bookmarked_page integer,
    start_page integer,
    file_name character varying(255),
    name character varying(255),
    language_level character varying(255),
    card_type character varying(255),
    CONSTRAINT sources_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS learn_language.cards (
    id character varying(255) NOT NULL,
    source_id character varying(255) NOT NULL,
    source_page_number integer NOT NULL,
    data jsonb NOT NULL,
    readiness character varying(255) NOT NULL,
    due timestamp(6) without time zone NOT NULL,
    stability real NOT NULL,
    difficulty real NOT NULL,
    elapsed_days real NOT NULL,
    scheduled_days real NOT NULL,
    learning_steps integer NOT NULL,
    reps integer NOT NULL,
    lapses integer NOT NULL,
    state character varying(255) NOT NULL,
    last_review timestamp(6) without time zone,
    CONSTRAINT cards_pkey PRIMARY KEY (id),
    CONSTRAINT card_source_id_fkey FOREIGN KEY (source_id) REFERENCES learn_language.sources(id)
);

CREATE TABLE IF NOT EXISTS learn_language.review_logs (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    rating integer NOT NULL,
    review_duration integer,
    review_datetime timestamp(6) without time zone NOT NULL,
    card_id character varying(255) NOT NULL,
    CONSTRAINT review_logs_pkey PRIMARY KEY (id),
    CONSTRAINT review_log_card_id_fkey FOREIGN KEY (card_id) REFERENCES learn_language.cards(id)
);

DROP TABLE IF EXISTS learn_language.model_response_logs;

CREATE TABLE IF NOT EXISTS learn_language.model_usage_logs (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_name character varying(255) NOT NULL,
    model_type character varying(50) NOT NULL,
    operation_type character varying(255) NOT NULL,
    input_tokens bigint,
    output_tokens bigint,
    input_characters bigint,
    image_count integer,
    cost_usd numeric(10, 6),
    processing_time_ms bigint,
    response_content text,
    rating integer,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT model_usage_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE learn_language.model_usage_logs ADD COLUMN IF NOT EXISTS rating integer;
