server:
  forward-headers-strategy: framework
  shutdown: graceful
management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
spring:
  application:
    name: expense-tracker
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  boot:
    admin:
      client:
        url: http://${SPRING_ADMIN_SERVER_HOST}:${SPRING_ADMIN_SERVER_PORT}
        instance:
          name: expense-tracker
          service-base-url: http://${K8S_POD_IP}:8080
          management-base-url: http://${K8S_POD_IP}:${SPRING_ACTUATOR_PORT}
        auto-deregistration: true