package io.github.mucsi96.learnlanguage.model.anki;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Decks generated by hbm2java
 */
@Entity
@Table(name = "decks", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Decks implements java.io.Serializable {

    private long id;
    private String name;
    private int mtimeSecs;
    private int usn;
    private String common;
    private String kind;

    public Decks() {
    }

    public Decks(long id, String name, int mtimeSecs, int usn, String common, String kind) {
        this.id = id;
        this.name = name;
        this.mtimeSecs = mtimeSecs;
        this.usn = usn;
        this.common = common;
        this.kind = kind;
    }

    @Id
    @Column(name = "id", nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false, length = 2000000000)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "mtime_secs", nullable = false)
    public int getMtimeSecs() {
        return this.mtimeSecs;
    }

    public void setMtimeSecs(int mtimeSecs) {
        this.mtimeSecs = mtimeSecs;
    }

    @Column(name = "usn", nullable = false)
    public int getUsn() {
        return this.usn;
    }

    public void setUsn(int usn) {
        this.usn = usn;
    }

    @Column(name = "common", nullable = false, length = 2000000000)
    public String getCommon() {
        return this.common;
    }

    public void setCommon(String common) {
        this.common = common;
    }

    @Column(name = "kind", nullable = false, length = 2000000000)
    public String getKind() {
        return this.kind;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

}
