package io.github.mucsi96.learnlanguage.model.anki;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Fields generated by hbm2java
 */
@Entity
@Table(name="fields"
    , uniqueConstraints = @UniqueConstraint(columnNames={"name", "ntid"}) 
)
public class Fields  implements java.io.Serializable {


     private FieldsId id;
     private String name;
     private String config;

    public Fields() {
    }

    public Fields(FieldsId id, String name, String config) {
       this.id = id;
       this.name = name;
       this.config = config;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ntid", column=@Column(name="ntid", nullable=false) ), 
        @AttributeOverride(name="ord", column=@Column(name="ord", nullable=false) ) } )
    public FieldsId getId() {
        return this.id;
    }
    
    public void setId(FieldsId id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=2000000000)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="config", nullable=false, length=2000000000)
    public String getConfig() {
        return this.config;
    }
    
    public void setConfig(String config) {
        this.config = config;
    }




}


