package io.github.mucsi96.learnlanguage.model.anki;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Graves generated by hbm2java
 */
@Entity
@Table(name="graves"
)
public class Graves  implements java.io.Serializable {


     private GravesId id;
     private int usn;

    public Graves() {
    }

    public Graves(GravesId id, int usn) {
       this.id = id;
       this.usn = usn;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="oid", column=@Column(name="oid", nullable=false) ), 
        @AttributeOverride(name="type", column=@Column(name="type", nullable=false) ) } )
    public GravesId getId() {
        return this.id;
    }
    
    public void setId(GravesId id) {
        this.id = id;
    }

    
    @Column(name="usn", nullable=false)
    public int getUsn() {
        return this.usn;
    }
    
    public void setUsn(int usn) {
        this.usn = usn;
    }




}


