package io.github.mucsi96.learnlanguage.model.anki;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Revlog generated by hbm2java
 */
@Entity
@Table(name="revlog"
)
public class Revlog  implements java.io.Serializable {


     private int id;
     private int cid;
     private int usn;
     private int ease;
     private int ivl;
     private int lastIvl;
     private int factor;
     private int time;
     private int type;

    public Revlog() {
    }

    public Revlog(int id, int cid, int usn, int ease, int ivl, int lastIvl, int factor, int time, int type) {
       this.id = id;
       this.cid = cid;
       this.usn = usn;
       this.ease = ease;
       this.ivl = ivl;
       this.lastIvl = lastIvl;
       this.factor = factor;
       this.time = time;
       this.type = type;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="cid", nullable=false)
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }

    
    @Column(name="usn", nullable=false)
    public int getUsn() {
        return this.usn;
    }
    
    public void setUsn(int usn) {
        this.usn = usn;
    }

    
    @Column(name="ease", nullable=false)
    public int getEase() {
        return this.ease;
    }
    
    public void setEase(int ease) {
        this.ease = ease;
    }

    
    @Column(name="ivl", nullable=false)
    public int getIvl() {
        return this.ivl;
    }
    
    public void setIvl(int ivl) {
        this.ivl = ivl;
    }

    
    @Column(name="lastIvl", nullable=false)
    public int getLastIvl() {
        return this.lastIvl;
    }
    
    public void setLastIvl(int lastIvl) {
        this.lastIvl = lastIvl;
    }

    
    @Column(name="factor", nullable=false)
    public int getFactor() {
        return this.factor;
    }
    
    public void setFactor(int factor) {
        this.factor = factor;
    }

    
    @Column(name="time", nullable=false)
    public int getTime() {
        return this.time;
    }
    
    public void setTime(int time) {
        this.time = time;
    }

    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }




}


