package io.github.mucsi96.learnlanguage.model.anki;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name="tags"
)
public class Tags  implements java.io.Serializable {


     private String tag;
     private int usn;
     private int collapsed;
     private String config;

    public Tags() {
    }

	
    public Tags(String tag, int usn, int collapsed) {
        this.tag = tag;
        this.usn = usn;
        this.collapsed = collapsed;
    }
    public Tags(String tag, int usn, int collapsed, String config) {
       this.tag = tag;
       this.usn = usn;
       this.collapsed = collapsed;
       this.config = config;
    }
   
     @Id 

    
    @Column(name="tag", unique=true, nullable=false, length=2000000000)
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }

    
    @Column(name="usn", nullable=false)
    public int getUsn() {
        return this.usn;
    }
    
    public void setUsn(int usn) {
        this.usn = usn;
    }

    
    @Column(name="collapsed", nullable=false)
    public int getCollapsed() {
        return this.collapsed;
    }
    
    public void setCollapsed(int collapsed) {
        this.collapsed = collapsed;
    }

    
    @Column(name="config", length=2000000000)
    public String getConfig() {
        return this.config;
    }
    
    public void setConfig(String config) {
        this.config = config;
    }




}


